package exo1corba;


/**
* exo1corba/HorlogeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* lundi 14 décembre 2015 09 h 34 CET
*/

public interface HorlogeOperations 
{
  String localite ();
  String getTime ();
  String getTimeZone ();
} // interface HorlogeOperations
