package exo1corba;


/**
* exo1corba/Horloge.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* lundi 14 décembre 2015 09 h 34 CET
*/

public interface Horloge extends HorlogeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Horloge
